### ISSUE TITLE
[1주차] 피드백

### ISSUE THREAD

**Issue by ujentus** [kimsin3003/X10#1]
- 출사표 (-1)
  헤헤헤헤가 뭐냠? 자신을 위한 goal이 없으면 나중에 뭘 이루었는지 알기가 힘들다. 반드시 설정하도록.
- 게임 컨셉 기획서 (-3)
  아직 임시 문서인 것 같다. 여러가지 내용으 막 섞여 있어서 마치 브레인스토밍한 것을 정리해놓은 것 같다. 
  이 것을 좀 더 구체화 시켜서, 개요/기획의도, 배경, 메커니즘, 플레이시나리오의 형태로 잘 정리해놓을 것. 이것이 잘 되어 있어야 나중에 팀원간 게임 콘텐츠 추가 우선순위에서 충돌이 발생할 때, 어느 것이 원래 추구하고자 한 비전에 더 적합한지 알 수 있게 된다. 
  플레이시나리오는 대략 방향을 잘 잡은것 같다. 게임 메커니즘에 더 명확해지면 저런식으로 풀어서 쓰면 된다. 
  다시 한 번 말하지만, 컨셉 기획서는 팀원이 아닌 제3자가 읽어도 어떤게임이지 머리속에 그려질 수 있어야 한다.
- 스터디 계획
  방향을 잘 잡았다. 스터디를 진행하면서 계속 업데이트 해 나갈 것! 중요한 것은 최신의 상태로 업데이트 해 나가는 것이고, 스터디 내용은 팀원 또는 팀간 정보 공유로도 쓰일 수 있어야 한다.
- 스터디 내용
  정작 cocos2d 스터디 내용은 거의 없네 ㅎㅎ STL관련 스터디 내용은 카페에 코멘트 달았음. 앞으로는 위키에 정리하기를 추천하다. 왜냐하면 검색이 되거든 ㅎㅎ (http://stackoverflow.com/questions/12535602/search-for-a-keyword-within-a-github-wiki)

**Comment by Myeongchan-Kim** [comment]
https://www.dropbox.com/s/0txlo8ixd96c8b5/%EA%B0%9C%EA%B2%BD%ED%94%84%20%EC%BB%A8%EC%85%89%20%EA%B8%B0%ED%9A%8D%EC%84%9C%20-%20X10.pptx?dl=0

발표용 ppt 입니다.. 아직 지속적으로 수정중이라 따로 안올렸었습니다.

**Comment by ujentus** [comment]
컨셉 기획이 수정/보완 되면 위키에도 지속적으로 업데이트 할 것~~
ppt 내용 확인: +1점

**Comment by FeatherHub** [comment]
확인했습니다

**Comment by FeatherHub** [comment]
다시열었습니다

**Comment by ujentus** [comment]
다 처리되면 닫아주삼.

**Comment by Myeongchan-Kim** [comment]
기획서 완성되면 닫겠습니다.

**Comment by Myeongchan-Kim** [comment]
기획서 https://www.dropbox.com/s/33f49bio0ive8kl/X10%20%EA%B8%B0%ED%9A%8D%EC%84%9C%20%28%EC%88%98%EC%A0%95%EC%A4%91%29.pptx?dl=0
