### ISSUE TITLE
안드로이드 포팅

### ISSUE THREAD

**Issue by Myeongchan-Kim** [kimsin3003/X10#119]
... 갈길이 멀구나... android-mc 브랜치 땄어요

**Comment by Myeongchan-Kim** [comment]
지금 armeabi 모듈이 현욱이 템플릿 문법을 이해를 못해서 컴파일이 안된다.. 여러가지 방법을 시도해보는중.

**Comment by Myeongchan-Kim** [comment]
to_string문제는 Application.mk 파일에
APP_STL := c++_static
NDK_TOOLCHAIN := arm-linux-androideabi-clang3.6
를 추가해서 해결함.

**Comment by jwvg0425** [comment]
헐 그래요? C++ 11 문법이 제대로 적용이 안되는건가.. 저 오늘 학교 가는데 혹시 학교 계시면 한 번 봐드릴게요

**Comment by Myeongchan-Kim** [comment]
세부 이슈들로 분해함.
