### ISSUE TITLE
메인화면에서 캐릭터 누르면 가로등 켜지기 직전에 멈춤.

### ISSUE THREAD

**Issue by Myeongchan-Kim** [kimsin3003/X10#123]
신기하게 가로등 켜지는 소리는 남

**Comment by FeatherHub** [comment]
여러 사소한 문제가 있었어요  
1. 파일명이 Title.png 인데 문자열에 title.png 로 저장되어 있었음  
2. setPosition 안에 매개변수를 Vec2로 감싸지 않고 숫자만 넣었음 ( ex: setPosition(100,100) )  
3. setPosition 안에 매개변수 float 표시를 모두 해줌 ( ex: 100 -> 100.0f )  
4. 아직 자식등록되지 않은 A를 B가 사용하고 있었음 ( ex: A, B, A->addChild(B), addChild(A) )  
정말 자잘한 것들이 발목을 잡았던 것네요

**Comment by Myeongchan-Kim** [comment]
굿굿
