### ISSUE TITLE
음악 저작권 문제 해결

### ISSUE THREAD

**Issue by kimsin3003** [kimsin3003/X10#129]

**Comment by Myeongchan-Kim** [comment]
나는 발자국 소리 했는데
이거 freeSFX.co.uk 에서 받은파일인데 Credit에 넣거나, 웹사이트 안내에 표시만 해달라네~
참고 :  

> Credit Required  You MUST credit freesfx.co.uk if you use our sound effects or music in your project. How you do this is up to you but please make sure that you include our website URL in your credit as follows:
> [http://www.freesfx.co.uk](url)
> If your project doesn't have a website or blog associated with it the credit back can be printed on any artwork for your project, added to the final credits for a film, added to your YouTube video description etc. If none of the above apply to you - you can always Tweet about us and let everyone know that you used our sounds. If you have any questions regarding this, please don't hesitate to contact us at hello@freesfx.co.uk

**Comment by Myeongchan-Kim** [comment]
태우는 유튜브 주인한테 허락맡고 크레딧에 넣음 ㅎㅎ 마무리!
