### ISSUE TITLE
아이콘 변경

### ISSUE THREAD

**Issue by Myeongchan-Kim** [kimsin3003/X10#131]
코코스 아이콘을 우리 아이콘으로 변경

**Comment by FeatherHub** [comment]
완료!  
근데 버전 컨트롤에는 추가하지 않고 해당 파일을 따로 압축하여 루트 디렉토리에 저장함  
(proj.android 폴더가 gitignore에 등록되어 있는데 이걸 풀면 동기화할 게 많아짐  
현재 동기화할 필요있는 폴더는 bin 하나여서 파일을 그냥 따로 뺌)
