### ISSUE TITLE
앱 이름 Quite Night 으로 바꾸기

### ISSUE THREAD

**Issue by Myeongchan-Kim** [kimsin3003/X10#132]
우째 바꾸노

**Comment by FeatherHub** [comment]
proj.android 에 androidmanifest.xml 을 들어가면 string/app_name 이라는 항목이 있는데 이것이 앱 이름인 것 같아요.  
어디서 설정하는지 찾아봤는데 proj.android/res/values 에 strings.xml 이라는 파일이 있더라구요  
그 안에 app_name 항목이 있어서 Quite Night로 바꿨습니다
