### ISSUE TITLE
각자 test page 추가

### ISSUE THREAD

**Issue by FeatherHub** [kimsin3003/X10#23]
MainScene우측 하단에 JW, TW, MC 버튼

**Comment by Myeongchan-Kim** [comment]
저는 보일듯 말듯한 졸라쪼그만 버튼 하나 종료버튼 위에 만들었어요
나머지 분들도 각자 달고 코멘트 달아주세요~

**Comment by FeatherHub** [comment]
Tw, Jw 추가 완료
