### ISSUE TITLE
init 함수 호출 시점

### ISSUE THREAD

**Issue by jwvg0425** [kimsin3003/X10#27]
우연히 지나가다가 4주차 회의록 보는데 보여서... cocos2d-x에서 init 함수는 create 함수 호출할 때 호출됩니다. 보통 특정 객체에 대한 create 함수를 만들 때 CREATE_FUNC 매크로를 쓰는데, 이 CREATE_FUNC 매크로가 만드는 코드를 보면 init에 대한 코드가 포함이 되어있어요.

``` C++
class TestNode : cocos2d::Node
{
public:
    CREATE_FUNC(TestNode);
};

TestNode* t = TestNode::create(); //여기서 init함수가 같이 호출됨

// CREATE_FUNC 매크로
#define CREATE_FUNC(__TYPE__) \
static __TYPE__* create() \
{ \
    __TYPE__ *pRet = new(std::nothrow) __TYPE__(); \
    if (pRet && pRet->init()) \   // <- 이 위치에서 init 함수가 호출이 됩니다. 결국 create 함수 내부에서 호출된다는 뜻
    { \
        pRet->autorelease(); \
        return pRet; \
    } \
    else \
    { \
        delete pRet; \
        pRet = nullptr; \
        return nullptr; \
    } \
}
```

CREATE_FUNC 같은 매크로로 create 함수를 만들어 쓰시는게 아니면 init함수는 명시적으로 호출해주셔야합니당

그리고 constexpr 같은 키워드가 붙은 함수가 아니면 컴파일타임에 함수가 실행되는 일은 없어요!

혹시 해결하신 이슈라면 뒷북이지만 혹시나 하여..

**Comment by jwvg0425** [comment]
근데 자세히 보니까 위키 아래쪽 글을 보니 해결하신 문제인거같네요 ㅋㅋ 뻘짓인듯

**Comment by ujentus** [comment]
good!

**Comment by Myeongchan-Kim** [comment]
맞슴다.. ㅠㅠ Init을 우리가 만든 클래스에서도 쓰는바람에 개헷갈림.. 어쩌지
