### ISSUE TITLE
기획 상세화

### ISSUE THREAD

**Issue by kimsin3003** [kimsin3003/X10#4]
컨셉, 게임 형태(pvp or ai대전)
프레임워크 설계.

**Comment by FeatherHub** [comment]
- 프로토타이핑 은 없이 바로 코코스로 갑시다

**Comment by kimsin3003** [comment]
https://github.com/kimsin3003/X10/wiki/3%EC%A3%BC%EC%B0%A8-%ED%9A%8C%EC%9D%98%EB%A1%9D
