### ISSUE TITLE
[2주차] 피드백

### ISSUE THREAD

**Issue by ujentus** [kimsin3003/X10#8]
1. 마일스톤 및 todo 이슈 정리가 미흡하다. (-2)
   세부 이슈는 일일이 못만들더라도 큰 그림은 꼭 그려야한다.
   다른 팀( https://github.com/atgchan/2015_GaeKyungPu/milestones ) 함 보삼.. 세부 이슈는 둘째치더라도 프로젝트의 큰 흐름을 주차별 마일스톤 제목으로 잘 뽑아놓은것 같지 않남?
   이런식으로 큰 그림을 꼭 그리도록..
2. 스터디 정리
   대체로 잘 하는 편이다. 중요한 것은 제 3자가 봐도 참고하고 이해할 수 있는 수준이어야 한다는 것.
   그런데, 위키에 정리하는 것 보니까, 아예 작성조차 되지 않은 페이지에 대한 링크가 많고, 미완성 상태의 페이지가 더러 보인다. 차라리 이런 페이지들은 <공사중> 표시를 하는건 어떨까?
3. 게임 컨셉 정리 (-1)
   여전히 지난주 내용 그대로이다... (<임시>표시되어 있고 정리보다는 습작처럼 끄적여(?) 놓은 느낌..)
   어디까지가 정해진 내용인지 감이 오지 않는다.
   지난 수업시간에 피드백 받은 것 고려하여  확정된 것 위주로 간략하게나마 업데이트 하도록..

위키에 정리하는 것은 지속적인 업데이트가 중요하다!! 한번 작성하고 땡~~ 인게 아니라 최신 상태에 맞게 지속적으로 업데이트하도록~! 

그리고, 처리된 이슈는 코멘트와 함께 꼭 닫아주삼.

**Comment by Myeongchan-Kim** [comment]
기획서 https://www.dropbox.com/s/33f49bio0ive8kl/X10%20%EA%B8%B0%ED%9A%8D%EC%84%9C%20%28%EC%88%98%EC%A0%95%EC%A4%91%29.pptx?dl=0

업데이트 하였습니다.
