### ISSUE TITLE
컨셉과 불릿 움직임이 어울리지 않는 문제

### ISSUE THREAD

**Issue by FeatherHub** [kimsin3003/X10#83]
화면을 넘어가면 불릿이 반대편에서 나온다거나  
Y거울에 부딪혀서 바닥으로 떨어진다거나 하는 불릿의 동작이  
게임을 대충 만들었군 하는 인상을 주는 것 같습니다.  

불릿이 바닥에 닿으면 주인공이 깜짝 놀라는 반응(다칠뻔했군 휴)을 보인다거나  
화면을 뚫고 지나갈 때 주인공이 깜짝 놀라는 반응(머어지?)을 보이면  
보정이 될 듯싶은데  
의견 있으신가요?

**Comment by Myeongchan-Kim** [comment]
음,, 불릿 이미지를 바꾸고.. (구글에 '스파클라' 검색)
미러에 팅길때 이펙트를 추가 하거나 다른 타겟들도 부딫힐때 이펙트를 수정및 추가 하면 괜찮지 않을까?
이것도 컨셉 바뀌면서 엎을 이슈긴 함..
