### ISSUE TITLE
재빌드 문제 점검.

### ISSUE THREAD

**Issue by ujentus** [kimsin3003/X10#9]
늬들~~ 3.2 버전 이상 쓰니? 그러면 PDB 파일 문제일수도 있으니 이걸 참고해보삼

http://discuss.cocos2d-x.org/t/cocos-3-2-how-to-stop-visual-studio-rebuilding-entire-cocos-every-time/15687

**Comment by FeatherHub** [comment]
서브 모듈 제대로 작동하는 것 확인
